FROM node:lts

EXPOSE 5000

ENV PROJECT=example-frontend

WORKDIR /usr/src/app

RUN git init && \
    git remote add -f origin https://github.com/docker-hy/material-applications.git && \
    git fetch origin && \
    git checkout origin/main -- $PROJECT

WORKDIR ./$PROJECT

RUN npm run build && \
    npm install && \
    npm install -g serve

CMD serve -s -l 5000 build
