version: "3.5"

services:
  redis:
    image: redis

  frontend:
    image: example-frontend:ubuntu
    build:
      context: ./frontend/
      dockerfile: Dockerfile.ubuntu
    ports:
      - 5000:5000

  backend:
    image: example-backend:ubuntu
    build:
      context: ./backend/
      dockerfile: Dockerfile.ubuntu
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
