version: "3.5"

services:
  training:
    image: ml-kurkkumopo-training
    volumes:
      - imgs:/src/imgs
      - data:/src/data
      - model:/src/model

  backend:
    image: ml-kurkkumopo-backend
    volumes:
      - model:/src/model
    ports:
      - 5000:5000

  frontend:
    image: ml-kurkkumopo-frontend
    ports:
      - 3000:3000

volumes:
  imgs:
  data:
  model:
